#!/usr/bin/env bash
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"
export CARGO_TERM_COLOR=never

: "${VPNNODE_BASELINE_REMOTE_EXIT_ADDR:?set VPNNODE_BASELINE_REMOTE_EXIT_ADDR}"
: "${VPNNODE_BASELINE_REMOTE_RELAY1_ADDR:?set VPNNODE_BASELINE_REMOTE_RELAY1_ADDR}"
: "${VPNNODE_BASELINE_REMOTE_RELAY2_ADDR:?set VPNNODE_BASELINE_REMOTE_RELAY2_ADDR}"

export VPNNODE_ROUTE_QUALITY_SERIES_COUNT="${VPNNODE_ROUTE_QUALITY_SERIES_COUNT:-3}"
export VPNNODE_ROUTE_QUALITY_SERIES_RUNS="${VPNNODE_ROUTE_QUALITY_SERIES_RUNS:-4}"
export VPNNODE_ROUTE_QUALITY_SERIES_PREFIX="${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX:-docs/artifacts/route_quality_series_2026-03-21}"
export VPNNODE_ROUTE_QUALITY_ROUTE_LENGTH="${VPNNODE_ROUTE_QUALITY_ROUTE_LENGTH:-3}"
export VPNNODE_BASELINE_REMOTE_EXACT_ROUTE_ONLY=false

cd "$(dirname "$0")/.."

echo "=== remote route-quality series ==="
echo "series_count=${VPNNODE_ROUTE_QUALITY_SERIES_COUNT}"
echo "runs_per_series=${VPNNODE_ROUTE_QUALITY_SERIES_RUNS}"
echo "relay1=${VPNNODE_BASELINE_REMOTE_RELAY1_ADDR}"
echo "relay2=${VPNNODE_BASELINE_REMOTE_RELAY2_ADDR}"
echo "exit=${VPNNODE_BASELINE_REMOTE_EXIT_ADDR}"
echo "route_length=${VPNNODE_ROUTE_QUALITY_ROUTE_LENGTH}"
echo "series_prefix=${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}"

for run in $(seq 1 "${VPNNODE_ROUTE_QUALITY_SERIES_COUNT}"); do
  echo "=== series ${run}/${VPNNODE_ROUTE_QUALITY_SERIES_COUNT} ==="
  export VPNNODE_ROUTE_QUALITY_RUNS="${VPNNODE_ROUTE_QUALITY_SERIES_RUNS}"
  export VPNNODE_ROUTE_QUALITY_LOCAL_LISTEN="127.0.0.1:$((19380 + run))"
  export VPNNODE_ROUTE_QUALITY_ROUTE_CACHE_PATH="route_cache_route_quality_series_${run}.json"
  export VPNNODE_ROUTE_QUALITY_RAW_PATH="${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}_run${run}.jsonl"
  export VPNNODE_ROUTE_QUALITY_STAGE_TRACE_PATH="${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}_run${run}.client.jsonl"
  export VPNNODE_ROUTE_QUALITY_REPORT_PATH="${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}_run${run}.md"
  bash scripts/run_route_quality_remote.sh
done

python scripts/summarize_route_quality_series.py \
  --stage-glob "${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}_run*.client.jsonl" \
  --json-out "${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}.jsonl" \
  --md-out "${VPNNODE_ROUTE_QUALITY_SERIES_PREFIX}.md"
